### PR TITLE
Reduce the number of warnings

### PR DESCRIPTION
**Pull request by pseudo-rnd-thoughts**
# Description

The CI reports 9000+ warnings
`======== 255 passed, 25 deselected, 9585 warnings in 284.66s (0:04:44) =========`

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
Changes: 
1. Update `google.cloud.storage.download_as_string` to `download_as_bytes` 
2. Fix registry overwrite using `pytest.fixture`
3. Add pytest warning ignore in pyproject.toml 

`========= 255 passed, 25 deselected, 10 warnings in 263.37s (0:04:23) ==========`

**Review by younik — COMMENTED** [review]
Everything looks good to me; any idea why now the tutorial is failing? 🤔

**Comment by pseudo-rnd-thoughts** [comment]
It appears to be linked to an updated yesterday of `imageio.ffpmeg` that was fixed the same day
We had the same issue on Gymnasium and just re-running the CI fixed it

**Review by younik — APPROVED** [review]
Oh okay
Feel free to merge it

**Pull request merged**
