### PR TITLE
Added option to copy data when combining datasets

### PR DESCRIPTION
**Pull request by Howuhh**
# Description

Related to https://github.com/Farama-Foundation/Minari/issues/56 

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have run `pytest -v` and no errors are present.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Howuhh** [comment]
a bit uglier than initially, but unfortunately because of the limitations of h5py you can't do it like in the first commit

**Review by balisujohn — CHANGES_REQUESTED** [review]
Overall, it looks good, and it seems to perform as intended, creating combined datasets that are not broken when the source datasets are deleted.

I think also it would be good to include a test that makes sure the true-copied combined dataset is still intact after deleting the source datasets.

In a future PR, I think the true copy behavior should be made the default for the `combine_datasets()` function, and also the default for the `combine` command in the cli, though it should still be possible to enable the external link combination behavior in the cli with the optional flag` --external-link` I think we should make there be a check to see if combined datasets depend on other datasets, because right now you can break combined datasets with no warning by deleting their dependency datasets using `minari delete`. 

Curious to hear your thoughts on this.

**Review by balisujohn — APPROVED** [review]

**Comment by balisujohn** [comment]
LGTM :^)

**Comment by balisujohn** [comment]
@Howuhh Thanks for your thoughts on this.  I can understand the argument against switching to true copy as the primary method, so I'll hold off on making that change for the time being. I will make a task to add am optional  command line flag to enable true copy to the cli command `minari combine`.

**Pull request merged**
