### PR TITLE
Update pre-commit to check for all things gymnasium/pettingzoo does

### PR DESCRIPTION
**Pull request by elliottower**
# Description
Just figure might as well mirror things, the validate github workflows one I have found to be extremely helpful in local testing when making new CI stuff, and there's some other QOL stuff and making it cleaner

Fixes # (issue), Depends on # (pull request)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

### Screenshots

> Please attach before and after screenshots of the change if applicable.
> To upload images to a PR -- simply drag and drop or copy paste.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have run `pytest -v` and no errors are present.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by elliottower** [comment]
@younik these two pre-commit hooks are failing on my local machine but seem to pass on here, not sure what to make of it. It seems pretty odd to have stuff like !pip install in a .py file because strictly speaking that's improper syntax unless it's a .ipynb, but maybe it's fine because the tutorials can be downloaded as an .ipynb
pycharm64_0WHZZ5g1wk

**Review by elliottower — COMMENTED** [review]
Just looked through all the files to make sure there aren’t any extra changes besides removing white space and such, there’s some weird “deleted then re added the same thing” for svgs but don’t think it’s a problem

**Comment by younik** [comment]
> @younik these two pre-commit hooks are failing on my local machine but seem to pass on here, not sure what to make of it. It seems pretty odd to have stuff like !pip install in a .py file because strictly speaking that's improper syntax unless it's a .ipynb, but maybe it's fine because the tutorials can be downloaded as an .ipynb
> pycharm64_0WHZZ5g1wk

The tutorial was done for Jupyter notebook at the beginning but, yes, it is weird epecially because you can also download the .py version. I will fix it to work in python.

**Comment by elliottower** [comment]
> > @younik these two pre-commit hooks are failing on my local machine but seem to pass on here, not sure what to make of it. It seems pretty odd to have stuff like !pip install in a .py file because strictly speaking that's improper syntax unless it's a .ipynb, but maybe it's fine because the tutorials can be downloaded as an .ipynb
> > pycharm64_0WHZZ5g1wk
> 
> The tutorial was done for Jupyter notebook at the beginning but, yes, it is weird epecially because you can also download the .py version. I will fix it to work in python.

Just bumping in case you forgot about this (not a huge deal but probably good to get these pre-commit hooks up to date)

**Comment by elliottower** [comment]
Also it might be worth doing pre-commit autoupdate to see if anything is old

**Review by younik — APPROVED** [review]

**Pull request merged**
