### PR TITLE
ENH: EpisodeData as dataclass

### PR DESCRIPTION
**Pull request by younik**
# Description

Make `EpisodeData` a dataclass instead of `NamedTuple` and implement `__repr__` method as suggested in https://github.com/Farama-Foundation/Minari/issues/79

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have run `pytest -v` and no errors are present.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by balisujohn — COMMENTED** [review]
I think it would be good to add a test for this, but otherwise it looks good to me.

**Comment by younik** [comment]
> I think it would be good to add a test for this, but otherwise it looks good to me.

I added a test for it, thanks!

For testing, I copied the list of spaces that you used in your PR and added them to a file `test_common`; if we merge this first, you should update your `test_serialization` to use it

**Comment by balisujohn** [comment]
Thanks for the test. I like the shared dependency for the test spaces so we avoid repeating definitions, I'll copy this pattern for the Dummy space registration for the unflattened spaces PR. 

For the new test, can you also add an assert to the test that checks to see that the `repr` matches the expected `repr` string for each space?

**Comment by younik** [comment]
> Thanks for the test. I like the shared dependency for the test spaces so we avoid repeating definitions, I'll copy this pattern for the Dummy space registration for the unflattened spaces PR.
> 
> For the new test, can you also add an assert to the test that checks to see that the `repr` matches the expected `repr` string for each space?

done

**Review by balisujohn — APPROVED** [review]
LGTM :^)

**Pull request merged**
